### ISSUE TITLE
不是很明白封装成Framework的意义

### ISSUE THREAD

**Issue by maxfong** [81516741/LDHotfixTool#1]
[LDHotfixTool registerHotfix]内添加fixInstanceMethodBefore，fixInstanceMethodReplace之类的方法，值得打成Framework嘛？

**Comment by 81516741** [comment]
😀，不值得，这个代码网上一大堆的我只是用来测试下pod上传framework，然后下载下来会不会有问题

**Comment by maxfong** [comment]
好的
